id: I4248CFB8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:53:17+00:00'
last_modified: '2022-06-15T18:12:14.824615+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20730
  title: ས་སྐྱའི་མཁས་གྲུབ་ཆེན་པོ་ཁག་གསུམ་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    91EA:
      image_group_id: I8LS20737
      title: Volume 1 of sa skya'i mkhas grub chen po khag gsum gyi rnam thar/
      total_pages: 174
      order: 1
      base_file: 91EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
